[package]
name = "splinetoy"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2018"

[dependencies]
druid = "0.6"
serde_json = "1.0.60"
spline = { version = "0.3.0", features=["serde"], path = ".."}
